import "./globals.css";
import Link from "next/link";
import { archivo, inter } from "./font";
import Navigation from "./navigation";
import { Header, MenuProvider } from "./header";
import Footer from "./footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuProvider>
          <Header />
          {children}
          <Footer />
          <Navigation />
        </MenuProvider>
      </body>
    </html>
  );
}
