import "./globals.css";
import Link from "next/link";
import { archivo, inter } from "./font";
import Navigation from "./navigation";
import Header from "./header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer className="footer">
          <Link
            style={{
              fontSize: "0.8rem",
              fontWeight: 500,
            }}
            target="_blank"
            className={archivo.className}
            href="https://www.linkedin.com/in/andrei-dimaano/"
          >
            LINKEDIN
          </Link>
          <Link
            style={{
              fontSize: "0.8rem",
              fontWeight: 500,
            }}
            target="_blank"
            className={archivo.className}
            href="https://github.com/andreidimaano"
          >
            GITHUB
          </Link>
        </footer>
        <Navigation />
      </body>
    </html>
  );
}
